# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user1',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user2',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='userapp.UserProfile'),
            preserve_default=False,
        ),
    ]
