# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20170331_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='chatapp.ChatRoom'),
        ),
    ]
